/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SMK TELKOM
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hapus = new javax.swing.JToggleButton();
        keluar = new javax.swing.JToggleButton();
        proses = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        diskon = new javax.swing.JTextField();
        hb4 = new javax.swing.JTextField();
        hb3 = new javax.swing.JTextField();
        hb2 = new javax.swing.JTextField();
        hb1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 60, 14);

        jLabel2.setText("Diskon");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 190, 80, 14);

        jLabel3.setText("Hasil Barang 1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 60, 80, 14);

        jLabel4.setText("Hasil Barang 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 90, 80, 14);

        jLabel5.setText("Hasil Barang 3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 120, 80, 14);

        jLabel6.setText("Hasil Barang 4");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 150, 80, 14);

        hapus.setText("Hapus");
        getContentPane().add(hapus);
        hapus.setBounds(150, 240, 63, 23);

        keluar.setText("Keluar");
        getContentPane().add(keluar);
        keluar.setBounds(280, 240, 63, 23);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(30, 240, 65, 23);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 290, 166, 96);
        getContentPane().add(diskon);
        diskon.setBounds(149, 190, 120, 20);
        getContentPane().add(hb4);
        hb4.setBounds(149, 150, 120, 20);
        getContentPane().add(hb3);
        hb3.setBounds(149, 120, 120, 20);
        getContentPane().add(hb2);
        hb2.setBounds(149, 90, 120, 20);
        getContentPane().add(hb1);
        hb1.setBounds(149, 60, 120, 20);

        jTextField6.setText("jTextField1");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(180, 60, 59, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        int barang1 = Integer.parseInt (hb1.getText());
        int barang2 = Integer.parseInt (hb2.getText());
        int barang3 = Integer.parseInt (hb3.getText());
        int barang4 = Integer.parseInt (hb4.getText());
        int Diskon = Integer.parseInt (diskon.getText());
        int Harga = barang1 + barang2 + barang3 + barang4;
        String keterangan = "";
        if(Diskon == 50){
            int hasil = Harga / 2;
            keterangan ="\n Total harga: "+Harga+"\n total bayar= "+ hasil;
        }
        else if(Diskon == 75){
            int hasil = Harga * Diskon / 100;
            keterangan = "\n Total harga: "+Harga+"\n total bayar= "+ hasil;
        }
        else if (Diskon == 100){
            int hasil = Harga * 0;
            keterangan = "\n Total harga: "+Harga+"\n total bayar= "+ hasil;
        }
        else if (Diskon == 0){
            int hasil = Harga;
            keterangan = "\n Total harga: "+Harga+"\n total bayar= "+ hasil;
        }
        else{
            keterangan = " ";
        }
        TA.setText("Harga barang 1: "+barang1+"\n Harga barang 2: "+barang2+
                "\n Harga barang 3: "+barang3+"\n Harga barang 4: "+barang4+
                "\n Diskon anda : "+Diskon+keterangan);
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField diskon;
    private javax.swing.JToggleButton hapus;
    private javax.swing.JTextField hb1;
    private javax.swing.JTextField hb2;
    private javax.swing.JTextField hb3;
    private javax.swing.JTextField hb4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton keluar;
    private javax.swing.JToggleButton proses;
    // End of variables declaration//GEN-END:variables
}
